
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for production deployment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://nabzkoeoawdpttveuklq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hYnprb2VvYXdkcHR0dmV1a2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjE5MDQsImV4cCI6MjA3MTEzNzkwNH0.3B7vpLU9SDrVNxqIgNqhEVRbEcotck4F71bx3xB2L50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
